# Generated by Django 4.2.7 on 2026-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order', 'slide_number']},
        ),
        migrations.AddField(
            model_name='presentation',
            name='json_structure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='presentation',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='target_audience',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presentation',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('academic', 'Academic'), ('persuasive', 'Persuasive')], default='professional', max_length=50),
        ),
        migrations.AddField(
            model_name='presentation',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='bullets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title Slide'), ('content', 'Content Slide'), ('section', 'Section Divider'), ('conclusion', 'Conclusion Slide')], default='content', max_length=20),
        ),
        migrations.AddField(
            model_name='slide',
            name='speaker_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='visuals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
