# Generated by Django 4.2.7 on 2026-01-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0004_add_noto_nastaliq_urdu_font'),
        ('presentation_app', '0004_expand_font_choices'),
    ]

    operations = [
    ]
