# Generated by Django 4.2.7 on 2026-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0005_merge_20260115_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='slide_ratio',
            field=models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1'), ('2:3', '2:3')], default='16:9', help_text='Slide aspect ratio', max_length=10),
        ),
        migrations.AddField(
            model_name='presentation',
            name='template',
            field=models.CharField(default='rose_elegance', help_text='Template name: rose_elegance, warm_spectrum, etc.', max_length=50),
        ),
    ]
