# Generated by Django 4.2.7 on 2026-01-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0007_presentation_bullet_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='template',
            field=models.CharField(default='warm_blue', help_text='Template name: warm_blue, rose_elegance, warm_spectrum, etc.', max_length=50),
        ),
    ]
